# Form implementation generated from reading ui file 'selectionWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_selectionWindow(object):
    def setupUi(self, selectionWindow):
        selectionWindow.setObjectName("selectionWindow")
        selectionWindow.resize(400, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(selectionWindow.sizePolicy().hasHeightForWidth())
        selectionWindow.setSizePolicy(sizePolicy)
        selectionWindow.setMinimumSize(QtCore.QSize(400, 200))
        selectionWindow.setMaximumSize(QtCore.QSize(400, 300))
        self.label = QtWidgets.QLabel(parent=selectionWindow)
        self.label.setGeometry(QtCore.QRect(30, 40, 71, 51))
        self.label.setObjectName("label")
        self.entryLineEdit = QtWidgets.QLineEdit(parent=selectionWindow)
        self.entryLineEdit.setGeometry(QtCore.QRect(110, 60, 191, 22))
        self.entryLineEdit.setObjectName("entryLineEdit")
        self.selectButton = QtWidgets.QPushButton(parent=selectionWindow)
        self.selectButton.setGeometry(QtCore.QRect(150, 120, 93, 28))
        self.selectButton.setObjectName("selectButton")

        self.retranslateUi(selectionWindow)
        QtCore.QMetaObject.connectSlotsByName(selectionWindow)

    def retranslateUi(self, selectionWindow):
        _translate = QtCore.QCoreApplication.translate
        selectionWindow.setWindowTitle(_translate("selectionWindow", "Form"))
        self.label.setText(_translate("selectionWindow", "File Name:"))
        self.selectButton.setText(_translate("selectionWindow", "Select"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    selectionWindow = QtWidgets.QWidget()
    ui = Ui_selectionWindow()
    ui.setupUi(selectionWindow)
    selectionWindow.show()
    sys.exit(app.exec())
